version: '3.9'
services:
  redis:
    image: redislabs/rejson:2.2.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/bitname/redis/data
  postgres:
    image: postgres:13
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    image: nfl-scrape/backend:latest
    volumes:
      - ./backend/backend:/backend
    environment:
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - postgres
volumes:
  redis:
  postgres:
